[package]
name = "pscan"
version = "0.1.0"
authors = ["Jukka Taimisto <jtaimisto@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap="2.33.0"
log="0.4"
env_logger="0.7.1"
cidr= {version = "0.1", default-features=false}
async-std = { version = "1.9", features=["attributes", "unstable"]}
serde_json = {version = "1.0"}
serde = { version="1.0", features = ["derive"]}
signal-hook-async-std = { version="0.2"}
signal-hook = {version="0.3"}

